# LU selected solver

In [ ]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

from sdr.utils import matrix_generation

In [53]:
import numpy as np

def modify_array(arr):
    # Modify the array in-place
    #arr[0] = 99
    arr = np.array([0,0,0])


# Create a NumPy array
my_array = np.array([1, 2, 3])

# Call the function, which modifies the array in-place
modify_array(my_array)

# Changes made inside the function affect the original array
print("Modified Array:", my_array)


Modified Array: [1 2 3]


In [56]:
def modify_array(arr):
    # Modify the array in-place
    #arr[0] = 99
    arr = np.array([0,0,0])
    return arr


# Create a NumPy array
my_array = np.array([1, 2, 3])

# Call the function, which modifies the array in-place
my_array = modify_array(my_array)

# Changes made inside the function affect the original array
print("Modified Array:", my_array)

Modified Array: [0 0 0]


In [20]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Swap pointers without swapping data
def swap_pointers(array1, array2):
    return array2, array1

# Call the function and assign the returned values back to the original variables
array1, array2 = swap_pointers(array1, array2)

# Print the arrays to verify the swap
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [4 5 6]
Array 2: [1 2 3]


In [63]:
def func(a):
     return a

A = np.array([1, 2, 3])
L = func(A)

print(L)
A[0] =-2
print(L)

[1 2 3]
[-2  2  3]


In [67]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Swap pointers without swapping data
def swap_pointers(array1, array2):
    array1, array2 = array2, array1
    
    return array1

array3 = swap_pointers(array1, array2)
     
# Print the arrays to verify the swap
print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)

Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [4 5 6]


In [74]:
import numpy as np
import scipy.linalg as la
from sdr.utils import matrix_generation

def test_function(    
    A: np.ndarray,
    overwrite: bool = True,
) -> np.ndarray:
    
    if(overwrite == False):
        A_temp = np.copy(A)  # create temporary copy of A

    #print("in test function.")
    A[0:A.shape[0], 0:A.shape[1]] = la.cholesky(A).T
    #A = la.cholesky(A).T
    #print(A)
    
    if(overwrite == False):
        #print("before pointer swap.")
        #print(A_temp)
        A_temp, A = A, A_temp  
        #print("after pointer swap.")
        #print(A_temp)
        print("print A after swapping.")
        print(A)

        return A_temp
    
    else: 
        return A


nblocks = 1
blocksize = 5
symmetric = True
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_blocktridiag(
    nblocks, blocksize, symmetric, diagonal_dominant, seed
)

print(A)

L = test_function(A, overwrite=False)
print("Cholesky factor L.")
print(L)

print("original matrix A after calling factorization. overwrite = false.")
print(A)

#test_function(A)

#print("original matrix A after calling factorization. overwrite = true.")
#print(A)
#print("Cholesky factor L.")
#print(L)





[[5.32718045 0.89625805 0.13737308 0.97951756 1.09826766]
 [0.89625805 5.15084963 0.99496278 1.11770608 1.11757559]
 [0.13737308 0.99496278 6.45728164 0.68738679 1.54402094]
 [0.97951756 1.11770608 0.68738679 7.75093757 1.46823026]
 [1.09826766 1.11757559 1.54402094 1.46823026 6.00194068]]
print A after swapping.
[[5.32718045 0.89625805 0.13737308 0.97951756 1.09826766]
 [0.89625805 5.15084963 0.99496278 1.11770608 1.11757559]
 [0.13737308 0.99496278 6.45728164 0.68738679 1.54402094]
 [0.97951756 1.11770608 0.68738679 7.75093757 1.46823026]
 [1.09826766 1.11757559 1.54402094 1.46823026 6.00194068]]
Cholesky factor L.
[[2.30806855 0.         0.         0.         0.        ]
 [0.38831518 2.23608161 0.         0.         0.        ]
 [0.05951863 0.43462224 2.50296678 0.         0.        ]
 [0.42438842 0.42615154 0.19053902 2.71162715 0.        ]
 [0.47583841 0.41715844 0.53312468 0.36396456 2.27701673]]
original matrix A after calling factorization. overwrite = false.
[[2.30806855 0.   

In [1]:
import numpy as np
import scipy.linalg as la
from sdr.utils import matrix_generation


nblocks = 1
blocksize = 5
symmetric = True
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_blocktridiag(
    nblocks, blocksize, symmetric, diagonal_dominant, seed
)

print(A)


def test_function(
    overwrite: bool = True,
) -> np.ndarray:
    
    print("in test function.")
    print(A)
    if(overwrite == False):
        A_temp = np.copy(A)  # create temporary copy of A

    #print("in test function.")
    A[0:A.shape[0], 0:A.shape[1]] = la.cholesky(A).T
    #B = la.cholesky(A).T
    #print(A)
    
    A_temp, A = A, A_temp  
    
    # if(overwrite == False):
    #     #print("before pointer swap.")
    #     #print(A_temp)
    #     A_temp, A = A, A_temp  
    #     #print("after pointer swap.")
    #     #print(A_temp)
    #     print("print A after swapping.")
    #     print(A)

        #return A_temp
    
    #else: 
        #return A


#test_function(A)

#print("original matrix A after calling factorization. overwrite = true.")
#print(A)
#print("Cholesky factor L.")
#print(L)


L = test_function(overwrite=False)
print("Cholesky factor L.")
print(L)

print("original matrix A before calling factorization. overwrite = false.")
print(A)




[[5.32718045 0.89625805 0.13737308 0.97951756 1.09826766]
 [0.89625805 5.15084963 0.99496278 1.11770608 1.11757559]
 [0.13737308 0.99496278 6.45728164 0.68738679 1.54402094]
 [0.97951756 1.11770608 0.68738679 7.75093757 1.46823026]
 [1.09826766 1.11757559 1.54402094 1.46823026 6.00194068]]
in test function.
[[5.32718045 0.89625805 0.13737308 0.97951756 1.09826766]
 [0.89625805 5.15084963 0.99496278 1.11770608 1.11757559]
 [0.13737308 0.99496278 6.45728164 0.68738679 1.54402094]
 [0.97951756 1.11770608 0.68738679 7.75093757 1.46823026]
 [1.09826766 1.11757559 1.54402094 1.46823026 6.00194068]]
Cholesky factor L.
None
original matrix A before calling factorization. overwrite = false.
[[2.30806855 0.         0.         0.         0.        ]
 [0.38831518 2.23608161 0.         0.         0.        ]
 [0.05951863 0.43462224 2.50296678 0.         0.        ]
 [0.42438842 0.42615154 0.19053902 2.71162715 0.        ]
 [0.47583841 0.41715844 0.53312468 0.36396456 2.27701673]]


## 1. Block tridiagonal matrix

In [36]:
import numpy as np
from scipy.linalg import lu_factor

# Create a sample matrix
A = np.array([[4, 3], [6, 3]])

# Perform LU decomposition with overwrite_a=True
lu, piv = lu_factor(A, overwrite_a=True)

# The original matrix A has been overwritten
print("Original matrix A after LU decomposition with overwrite_a=True:\n", A)

print(lu)

# Create a new sample matrix
B = np.array([[4, 3], [6, 3]])

# Perform LU decomposition with overwrite_a=False (default behavior)
lu, piv = lu_factor(B, overwrite_a=False)

# The original matrix B remains unchanged
print("\nOriginal matrix B after LU decomposition with overwrite_a=False:\n", B)

A.shape[0]

Original matrix A after LU decomposition with overwrite_a=True:
 [[4 3]
 [6 3]]
[[6.         3.        ]
 [0.66666667 1.        ]]

Original matrix B after LU decomposition with overwrite_a=False:
 [[4 3]
 [6 3]]


2

In [ ]:
%matplotlib widget

from sdr.lu.lu_decompose import lu_dcmp_tridiag
from sdr.lu.lu_solve import lu_slv_tridiag

nblocks = 5
blocksize = 2
symmetric = True
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_blocktridiag(
    nblocks, blocksize, symmetric, diagonal_dominant, seed
)

# P_ref, L_ref, U_ref = la.lu(A)
lu_ref, p_ref = la.lu_factor(A)
L_sdr, U_sdr = lu_dcmp_tridiag(A, blocksize)

n_rhs = 3
B = np.random.randn(A.shape[0], n_rhs)


# --- Solving ---

X_ref = la.lu_solve((lu_ref, p_ref), B)
# Is equivalent to..
# Y_ref = la.solve_triangular(L_ref, B, lower=True)
# X_ref = la.solve_triangular(U_ref, Y_ref, lower=False)

fig, ax = plt.subplots(1, 3)
fig.suptitle("LU selected solver for block tridiagonal matrices")
ax[0].set_title("X_ref: Scipy lu solver")
ax[0].matshow(X_ref)

X_sdr = lu_slv_tridiag(L_sdr, U_sdr, B, blocksize)
ax[1].set_title("X_sdr: Selected lu solver")
ax[1].matshow(X_sdr)

X_diff = X_ref - X_sdr
ax[2].set_title("X_diff: Difference between X_ref and X_sdr")
ax[2].matshow(X_diff)
fig.colorbar(ax[2].matshow(X_diff), ax=ax[2], label="Relative error", shrink=0.4)




## 2. Block tridiagonal arrowhead matrix

In [ ]:
from sdr.lu.lu_decompose import lu_dcmp_tridiag_arrowhead
from sdr.lu.lu_solve import lu_slv_tridiag_arrowhead

nblocks = 5
diag_blocksize = 3
arrow_blocksize = 2
symmetric = True
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_blocktridiag_arrowhead(
    nblocks, diag_blocksize, arrow_blocksize, symmetric, diagonal_dominant, 
    seed
)

# --- Decomposition ---
# P_ref, L_ref, U_ref = la.lu(A)
lu_ref, p_ref = la.lu_factor(A)
L_sdr, U_sdr = lu_dcmp_tridiag_arrowhead(A, diag_blocksize, arrow_blocksize)

n_rhs = 5
B = np.random.randn(A.shape[0], n_rhs)


# --- Solving ---
X_ref = la.lu_solve((lu_ref, p_ref), B)
# Is equivalent to..
# Y_ref = la.solve_triangular(L_ref, B, lower=True)
# X_ref = la.solve_triangular(U_ref, Y_ref, lower=False)

fig, ax = plt.subplots(1, 3)
fig.suptitle("LU selected solver for block tridiagonal arrowhead matrices")
ax[0].set_title("X_ref: Scipy lu solver")
ax[0].matshow(X_ref)

X_sdr = lu_slv_tridiag_arrowhead(L_sdr, U_sdr, B, diag_blocksize, arrow_blocksize)
ax[1].set_title("X_sdr: Selected lu solver")
ax[1].matshow(X_sdr)

X_diff = X_ref - X_sdr
ax[2].set_title("X_diff: Difference between X_ref and X_sdr")
ax[2].matshow(X_diff)
fig.colorbar(ax[2].matshow(X_diff), ax=ax[2], label="Relative error", shrink=0.4)

## 3. Block n-diagonals matrix

In [ ]:
from sdr.lu.lu_decompose import lu_dcmp_ndiags
from sdr.lu.lu_solve import lu_slv_ndiags

nblocks = 6
ndiags = 7
blocksize = 2
symmetric = False
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_block_ndiags(
    nblocks, ndiags, blocksize, symmetric, diagonal_dominant, seed
)

# --- Decomposition ---
P_ref, L_ref, U_ref = la.lu(A)
# lu_ref, p_ref = la.lu_factor(A)
L_sdr, U_sdr = lu_dcmp_ndiags(A, ndiags, blocksize)

## call solve now
n_rhs = 1
B = np.random.randn(A.shape[0], n_rhs)

Y_ref = la.solve_triangular(L_ref, B, lower=True)
X_ref = la.solve_triangular(U_ref, Y_ref, lower=False)
# X_ref = la.lu_solve((lu_ref, p_ref), B)

X_sdr = lu_slv_ndiags(L_sdr, U_sdr, B, ndiags, blocksize)
#print("norm(X_ref - X_sdr) = ", np.linalg.norm(X_ref - X_sdr))

fig, ax = plt.subplots(1, 3)
ax[0].set_title("X_ref: Reference lu solver")
ax[0].matshow(X_ref)

ax[1].set_title("X_sdr: Selected lu solver")
ax[1].matshow(X_sdr)

X_diff = X_ref - X_sdr
ax[2].set_title("X_diff: Difference between X_ref and X_sdr")
ax[2].matshow(X_diff)
fig.colorbar(ax[2].matshow(X_diff), ax=ax[2], label="Relative error", shrink=0.4)

plt.show()

## 4. Block n-diagonals arrowhead matrix

In [ ]:
from sdr.lu.lu_decompose import lu_dcmp_ndiags_arrowhead
from sdr.lu.lu_solve import lu_slv_ndiags_arrowhead

nblocks = 7
ndiags = 5
diag_blocksize = 3
arrow_blocksize = 2
symmetric = False
diagonal_dominant = True
seed = 63

A = matrix_generation.generate_ndiags_arrowhead(
    nblocks, ndiags, diag_blocksize, arrow_blocksize, symmetric, 
    diagonal_dominant, seed
)

# --- Decomposition ---
# P_ref, L_ref, U_ref = la.lu(A)
lu_ref, p_ref = la.lu_factor(A)
L_sdr, U_sdr = lu_dcmp_ndiags_arrowhead(A, nblocks, diag_blocksize, arrow_blocksize)

## call solve now
n_rhs = 3
B = np.random.randn(A.shape[0], n_rhs)

#Y_ref = la.solve_triangular(L_ref, B, lower=True)
#X_ref = la.solve_triangular(U_ref, Y_ref, lower=False)
X_ref = la.lu_solve((lu_ref, p_ref), B)

X_sdr = lu_slv_ndiags_arrowhead(L_sdr, U_sdr, B, ndiags, diag_blocksize, arrow_blocksize)
#print("norm(X_ref - X_sdr) = ", np.linalg.norm(X_ref - X_sdr))

fig, ax = plt.subplots(1, 3)
ax[0].set_title("X_ref: Reference lu solver")
ax[0].matshow(X_ref)

ax[1].set_title("X_sdr: Selected lu solver")
ax[1].matshow(X_sdr)

X_diff = X_ref - X_sdr
ax[2].set_title("X_diff: Difference between X_ref and X_sdr")
ax[2].matshow(X_diff)
fig.colorbar(ax[2].matshow(X_diff), ax=ax[2], label="Relative error", shrink=0.4)

plt.show()